# Generated by Django 4.2.8 on 2024-01-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('f_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
